 --1. List all patients who live in Seattle.
SELECT * 
FROM PATIENTS
WHERE CITY = 'Seattle'
 
--2. Find all medications where the dosage is greater than 50mg.
SELECT MED_ID, MEDICATION_NAME, DOSAGE  
FROM MEDICATIONS
WHERE REPLACE(DOSAGE,'mg','')::INT > 50
 
--3. Get all completed appointments in February 2024.
SELECT *
FROM APPOINTMENTS
WHERE STATUS = 'Completed' AND EXTRACT(MONTH FROM APPOINTMENT_DATE) = 2 AND EXTRACT(YEAR FROM APPOINTMENT_DATE) = 2024
--4. Show each doctor and how many appointments they completed.
SELECT D.DOCTOR_ID, D.DOCTOR_NAME, COUNT(A.APPOINTMENT_ID) AS NO_OF_APPOINTMENTS
FROM DOCTORS D
JOIN APPOINTMENTS A ON A.DOCTOR_ID = D.DOCTOR_ID
WHERE A.STATUS = 'Completed'
GROUP BY D.DOCTOR_ID
ORDER BY NO_OF_APPOINTMENTS DESC
 
--5. Find the most common diagnosis in the database.
SELECT DIAGNOSIS_CODE, COUNT(APPOINTMENT_ID) AS NO_OF_APPOINTMENTS
FROM DIAGNOSES
GROUP BY DIAGNOSIS_CODE
ORDER BY NO_OF_APPOINTMENTS DESC
LIMIT 1
 
--6. List the total billing amount per patient.
SELECT P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME, SUM(B.AMOUNT) AS TOTAL_BILLED
FROM PATIENTS P
JOIN APPOINTMENTS A ON A.PATIENT_ID = P.PATIENT_ID
JOIN BILLING B ON B.APPOINTMENT_ID = A.APPOINTMENT_ID
GROUP BY P.PATIENT_ID
ORDER BY TOTAL_BILLED DESC
 
--7. Which clinic location has the highest number of appointments?
SELECT D.CLINIC_LOCATION, COUNT(A.APPOINTMENT_ID) AS NO_OF_APPOINTMENTS
FROM DOCTORS D
JOIN APPOINTMENTS A ON A.DOCTOR_ID = D.DOCTOR_ID
GROUP BY D.CLINIC_LOCATION
ORDER BY NO_OF_APPOINTMENTS DESC
 
--8. Identify patients who have more than one diagnosis in 2024.
SELECT P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME, COUNT(DIAGNOSIS_CODE) AS NO_OF_DIAGNOSIS
FROM DIAGNOSES D
JOIN APPOINTMENTS A ON A.APPOINTMENT_ID = D.APPOINTMENT_ID
JOIN PATIENTS P ON P.PATIENT_ID = A.PATIENT_ID
WHERE EXTRACT(YEAR FROM A.APPOINTMENT_DATE) = 2024
GROUP BY P.PATIENT_ID
HAVING COUNT(DIAGNOSIS_CODE) > 1
 
--9. Rank doctors by total revenue generated.
SELECT D.DOCTOR_ID, D.DOCTOR_NAME, SUM(B.AMOUNT) AS TOTAL_REVENUE,
RANK() OVER(ORDER BY SUM(B.AMOUNT) DESC) AS REVENUE_RANK
FROM DOCTORS D
JOIN APPOINTMENTS A ON A.DOCTOR_ID = D.DOCTOR_ID
JOIN BILLING B ON B.APPOINTMENT_ID = A.APPOINTMENT_ID
GROUP BY D.DOCTOR_ID
 
--10. For each patient, show their most recent appointment.
SELECT P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME, MAX(A.APPOINTMENT_DATE) AS MOST_RECENT_APPOINTMENT
FROM PATIENTS P
JOIN APPOINTMENTS A ON A.PATIENT_ID = P.PATIENT_ID
GROUP BY P.PATIENT_ID
 
--11. Identify patients whose insurance covered less than 70% of their bill.
SELECT P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME, B.AMOUNT, B.INSURANCE_COVERED, (B.INSURANCE_COVERED*100)/B.AMOUNT AS "insurance_covered_%"
FROM PATIENTS P
JOIN APPOINTMENTS A ON A.PATIENT_ID = P.PATIENT_ID
JOIN BILLING B ON B.APPOINTMENT_ID = A.APPOINTMENT_ID
WHERE (B.INSURANCE_COVERED*100)/B.AMOUNT < 70
 
--12. Identify all diabetic patients and list their last medication renewal date.
WITH PATIENT_DIAGNOSES AS(
	SELECT P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME, D.DIAGNOSIS_CODE
	FROM PATIENTS P
	JOIN APPOINTMENTS A ON A.PATIENT_ID = P.PATIENT_ID
	JOIN DIAGNOSES D ON D.APPOINTMENT_ID = A.APPOINTMENT_ID
	WHERE D.DIAGNOSIS_CODE = 'E11'
)
SELECT PD.PATIENT_ID, PD.FIRST_NAME, PD.LAST_NAME, MAX(M.END_DATE) AS LAST_RENEWAL_DATE
FROM PATIENT_DIAGNOSES PD
JOIN MEDICATIONS M ON M.PATIENT_ID = PD.PATIENT_ID
GROUP BY PD.PATIENT_ID, PD.FIRST_NAME, PD.LAST_NAME
 
--13. Which doctor has the lowest no‑show rate?
WITH DOCTOR_NO_SHOW AS (
	SELECT D.DOCTOR_ID, D.DOCTOR_NAME, COUNT(A.APPOINTMENT_ID) as TOTAL_NO_SHOW_APPOINTMENTS
	FROM DOCTORS D
	JOIN APPOINTMENTS A ON A.DOCTOR_ID = D.DOCTOR_ID
	WHERE A.STATUS = 'No-show'
	GROUP BY D.DOCTOR_ID
	ORDER BY TOTAL_NO_SHOW_APPOINTMENTS ASC
),
DOCTOR_APPOINTMENTS AS (
	SELECT D.DOCTOR_ID, D.DOCTOR_NAME, COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
	FROM DOCTORS D 
	JOIN APPOINTMENTS A ON A.DOCTOR_ID = D.DOCTOR_ID
	GROUP BY D.DOCTOR_ID
)
SELECT DA.DOCTOR_ID, DA.DOCTOR_NAME, (DNS.TOTAL_NO_SHOW_APPOINTMENTS*100)/DA.TOTAL_APPOINTMENTS AS NO_SHOW_RATE
FROM DOCTOR_APPOINTMENTS DA
JOIN DOCTOR_NO_SHOW DNS ON DNS.DOCTOR_ID = DA.DOCTOR_ID
 
--14. Which age group has the highest incidence of hypertension (I10)?
WITH PATIENTS_AGE AS (
	SELECT *, EXTRACT(YEAR FROM AGE(CURRENT_DATE, DATE_OF_BIRTH)) AS AGE_YEARS
	FROM PATIENTS 
),
PATIENT_AGE_GROUP AS (
	SELECT *,
	CASE 
	WHEN AGE_YEARS < 18 THEN '0-17'
	WHEN AGE_YEARS BETWEEN 18 AND 34 THEN '18-34'
	WHEN AGE_YEARS BETWEEN 35 AND 49 THEN '35-49'
	WHEN AGE_YEARS BETWEEN 50 AND 64 THEN '50-64'
	ELSE '65+'
	END AS AGE_GROUP
	FROM PATIENTS_AGE
)
SELECT PG.AGE_GROUP, COUNT(A.PATIENT_ID) AS NO_OF_PATIENTS
FROM PATIENT_AGE_GROUP PG
JOIN APPOINTMENTS A ON A.PATIENT_ID = PG.PATIENT_ID
JOIN DIAGNOSES D ON D.APPOINTMENT_ID = A.APPOINTMENT_ID
WHERE D.DIAGNOSIS_CODE = 'I10'
GROUP BY PG.AGE_GROUP
ORDER BY NO_OF_PATIENTS DESC
LIMIT 1
 
--15. Which insurance provider covers the highest average amount?
SELECT P.INSURANCE_PROVIDER, ROUND(AVG(B.INSURANCE_COVERED),2) AS AVG_AMOUNT_COVERED
FROM PATIENTS P
JOIN APPOINTMENTS A ON A.PATIENT_ID = P.PATIENT_ID
JOIN BILLING B ON B.APPOINTMENT_ID = A.APPOINTMENT_ID
GROUP BY P.INSURANCE_PROVIDER
ORDER BY AVG_AMOUNT_COVERED DESC
LIMIT 1
 
--16. Determine peak days of the week for appointments.
SELECT TO_CHAR(APPOINTMENT_DATE,'Day') AS DAY_OF_WEEK, COUNT(APPOINTMENT_ID) AS NO_OF_APPOINTMENTS
FROM APPOINTMENTS
GROUP BY DAY_OF_WEEK
ORDER BY NO_OF_APPOINTMENTS DESC
 

--17. List patients whose total billing amount exceeds the average billing amount
SELECT P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME, SUM(B.AMOUNT) AS TOTAL_BILLED
FROM PATIENTS P
JOIN APPOINTMENTS A ON A.PATIENT_ID = P.PATIENT_ID
JOIN BILLING B ON B.APPOINTMENT_ID = A.APPOINTMENT_ID
GROUP BY P.PATIENT_ID
HAVING SUM(B.AMOUNT) > (
SELECT AVG(TOTAL_AMOUNT)
FROM (
SELECT SUM(AMOUNT) AS TOTAL_AMOUNT
FROM BILLING B
JOIN APPOINTMENTS A ON A.APPOINTMENT_ID = B.APPOINTMENT_ID
GROUP BY PATIENT_ID
)
)
ORDER BY TOTAL_BILLED DESC
 
--top diagnosis per clinic location 
WITH CLINIC_DIAGNOSIS_RANK AS (
SELECT DOC.CLINIC_LOCATION, D.DIAGNOSIS_CODE, COUNT(A.APPOINTMENT_ID) NO_OF_APPOINTMENTS,
RANK() OVER(PARTITION BY DOC.CLINIC_LOCATION ORDER BY COUNT(A.APPOINTMENT_ID) DESC) AS RANK_APPOINTMENTS
FROM DOCTORS DOC
JOIN APPOINTMENTS A ON A.DOCTOR_ID = DOC.DOCTOR_ID
JOIN DIAGNOSES D ON D.APPOINTMENT_ID = A.APPOINTMENT_ID
GROUP BY DOC.CLINIC_LOCATION, D.DIAGNOSIS_CODE
)
SELECT CLINIC_LOCATION, DIAGNOSIS_CODE, NO_OF_APPOINTMENTS
FROM CLINIC_DIAGNOSIS_RANK
WHERE RANK_APPOINTMENTS = 1
 
--Count the number of medications per patient
WITH PATIENT_MEDICATION AS (
SELECT P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME, COUNT(DISTINCT MEDICATION_NAME) AS NO_OF_MEDICATIONS_PER_PATIENT
FROM PATIENTS P
JOIN MEDICATIONS M ON M.PATIENT_ID = P.PATIENT_ID
GROUP BY P.PATIENT_ID
ORDER BY NO_OF_MEDICATIONS_PER_PATIENT ASC
)
SELECT NO_OF_MEDICATIONS_PER_PATIENT, COUNT(PATIENT_ID) NO_OF_PATIENTS
FROM PATIENT_MEDICATION
GROUP BY NO_OF_MEDICATIONS_PER_PATIENT
ORDER BY NO_OF_PATIENTS DESC
 
SELECT * FROM BILLING
 
SELECT * FROM DIAGNOSES
 
SELECT * FROM DOCTORS
 
SELECT * FROM APPOINTMENTS
 
SELECT * FROM PATIENTS
 
SELECT * FROM MEDICATIONS
 
/*
SELECT *
FROM APPOINTMENTS
WHERE STATUS = 'Completed' AND APPOINTMENT_DATE >= '2024-02-01'::DATE AND APPOINTMENT_DATE < '2024-01-03'::DATE
*/
